In [4]:
import mysql.connector
from mysql.connector import Error

def create_connection():
    try:
        connection = mysql.connector.connect(
            host="localhost",
            user="root",  # Replace with your actual username
            password="Punitpal@123",  # Replace with your actual password
            database="retail_sales"
        )
        if connection.is_connected():
            print("Successfully connected to the database")
            return connection
    except Error as e:
        print(f"Error: {e}")
        return None

def add_product(name, price, stock):
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        query = "INSERT INTO products (name, price, stock) VALUES (%s, %s, %s)"
        cursor.execute(query, (name, price, stock))
        connection.commit()
        cursor.close()
        connection.close()
        print("Product added successfully")
    else:
        print("Failed to add product due to connection issue")

def add_customer(name, email):
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        query = "INSERT INTO customers (name, email) VALUES (%s, %s)"
        cursor.execute(query, (name, email))
        connection.commit()
        cursor.close()
        connection.close()
        print("Customer added successfully")
    else:
        print("Failed to add customer due to connection issue")

def add_sale(customer_id, sale_date):
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        query = "INSERT INTO sales (customer_id, sale_date) VALUES (%s, %s)"
        cursor.execute(query, (customer_id, sale_date))
        connection.commit()
        cursor.close()
        connection.close()
        print("Sale added successfully")
    else:
        print("Failed to add sale due to connection issue")

def add_sale_detail(sale_id, product_id, quantity):
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        query = "INSERT INTO sales_details (sale_id, product_id, quantity) VALUES (%s, %s, %s)"
        cursor.execute(query, (sale_id, product_id, quantity))
        connection.commit()
        cursor.close()
        connection.close()
        print("Sale detail added successfully")
    else:
        print("Failed to add sale detail due to connection issue")

# Example Usage
add_product('Laptop', 80000.00, 10)
add_product('Smartphone', 30000.00, 20)
add_customer('John Doe', 'john@gamil.com')
add_customer('John Sina', 'janesina@outlook.com')
add_sale(1, '2024-12-01')
add_sale_detail(1, 1, 2)  # Sale of 2 Laptops in Sale ID 1
add_sale_detail(1, 2, 1)  # Sale of 1 Smartphone in Sale ID 1

Successfully connected to the database
Product added successfully
Successfully connected to the database
Product added successfully
Successfully connected to the database

DatabaseError: 1205 (HY000): Lock wait timeout exceeded; try restarting transaction

In [ ]:
def view_sales_details():
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        query = """
        SELECT 
            sales.sale_id, customers.name as customer_name, sales.sale_date, 
            products.name as product_name, sales_details.quantity
        FROM sales
        JOIN customers ON sales.customer_id = customers.customer_id
        JOIN sales_details ON sales.sale_id = sales_details.sale_id
        JOIN products ON sales_details.product_id = products.product_id
        """
        cursor.execute(query)
        results = cursor.fetchall()
        for row in results:
            print(row)
        cursor.close()
        connection.close()
    else:
        print("Failed to view sales details due to connection issue")

# Example Usage
view_sales_details()